import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

describe('current direct side-effect call baseline', () => {
  it('keeps pack.open and low-level SBC save/submit calls inside EA Adapters', async () => {
    const source = await readFile(path.join(root, 'src', 'userscript-entry.js'), 'utf8');
    const packAdapter = await readFile(path.join(root, 'src', 'adapters', 'ea', 'pack.js'), 'utf8');
    const playerPickAdapter = await readFile(path.join(root, 'src', 'adapters', 'ea', 'player-pick.js'), 'utf8');
    const sbcAdapter = await readFile(path.join(root, 'src', 'adapters', 'ea', 'sbc.js'), 'utf8');
    expect(source.match(/\bpackAdapter\.open\s*\(/g) || []).toHaveLength(1);
    expect(source.match(/\b(?:currentPack|selectedPack|pack)\.open\s*\(/g) || []).toHaveLength(0);
    expect(packAdapter.match(/\bpack\.open\s*\(/g) || []).toHaveLength(1);
    expect(source.match(/\bW\.services\.SBC\.saveChallenge\s*\(/g) || []).toHaveLength(0);
    expect(source.match(/\bW\.services\.SBC\.submitChallenge\s*\(/g) || []).toHaveLength(0);
    expect(sbcAdapter.match(/\bservice\.saveChallenge\s*\(/g) || []).toHaveLength(1);
    expect(sbcAdapter.match(/\bservice\.submitChallenge\s*\(/g) || []).toHaveLength(1);
    expect(source.match(/\bW\.services\.Item\.redeem\s*\(/g) || []).toHaveLength(0);
    expect(source.match(/\bW\.services\.Item\.confirmPlayerPickItemSelection\s*\(/g) || []).toHaveLength(0);
    expect(playerPickAdapter.match(/\bservice\.redeem\s*\(/g) || []).toHaveLength(1);
    expect(playerPickAdapter.match(/\bservice\.confirmPlayerPickItemSelection\s*\(/g) || []).toHaveLength(1);
    expect(source.match(/\bsaveChallengeSquad\s*\(/g) || []).toHaveLength(3);
    expect(source).toMatch(/function\s+prepareSbcSquad\s*\(/);
    expect(source).toContain('prepareOnly: true');
  });

  it('records the special workflow functions that still require migration', async () => {
    const source = await readFile(path.join(root, 'src', 'userscript-entry.js'), 'utf8');
    expect(source).toContain("from './adapters/index.js'");
    expect(source).not.toMatch(/from\s+['"]\.\/adapters\/ea\//);
    expect(source).not.toMatch(/\bwindow\.(?:localStorage|sessionStorage)\b/);
    expect(source).not.toMatch(/\b(?:W\.)?(?:repositories|services)[^\n;]*\.myPacks\b/);
    expect(source).not.toMatch(/\bW\.services\.Store\.getPacks\s*\(/);
    expect(source).not.toMatch(/\bW\.getAppMain\s*\(/);
    expect(source).not.toMatch(/function\s+(?:areFutServicesReady|hasFutMainDom|isMainFutControllerName)\s*\(/);
    expect(source).not.toMatch(/\bW\.g(?:ClickShield|PopupClickShield)\b/);
    expect(source).not.toMatch(/\bW\.repositories\.Item\.(?:getPileSize|numItemsInCache)\s*\(/);
    expect(source).not.toMatch(/\bW\.services\.Item\.(?:requestUnassignedItems|move)\s*\(/);
    expect(source).not.toMatch(/\bW\.services\.Localization\.localize\s*\(/);
    expect(source).not.toMatch(/\bW\.(?:services\.SBC|repositories\.Squad)\b/);
    expect(source).not.toMatch(/\bW\.services\.(?:UserSettings|Chemistry)\b/);
    expect(source).not.toMatch(/\bW\.(?:ItemPile|PlayerInjury)\b/);
    expect(source).not.toMatch(/\bW\.[A-Za-z_$][A-Za-z0-9_$]*/);
    expect(source).toContain("const inventoryPile = (pileName) => eaInventoryAdapter().pileValue(pileName);");
    expect(source).toContain('eaInventoryAdapter().preparePurchasedItem(item);');
    expect(source).toContain('eaInventoryAdapter().capacity(pileName).free');
    expect(source).toContain('eaInventoryAdapter().requestUnassigned()');
    expect(source).toContain('eaInventoryAdapter().refreshActions(pileName)');
    expect(source).toContain('eaInventoryAdapter().move(items, pile, allowStorage)');
    expect(source).toContain('return localizationAdapter.localize(value);');
    expect(source).toContain('const pageRuntime = adapters.page;');
    expect(source).toContain('return pageRuntime.currentController();');
    expect(source).toContain('return pageRuntime.isReady();');
    expect(source).toContain('return pageRuntime.navigationController();');
    expect(source).toContain('pageRuntime.popupShieldShowing()');
    expect(source).toContain('return eaPackAdapter().list();');
    expect(source).toContain('eaPackAdapter().refreshAll()');
    expect(source).toMatch(/function\s+readInventoryPile\s*\([^)]+\)[\s\S]*?eaInventoryAdapter\(\)\.readPile\(pileName\)/);
    expect(source.match(/return readInventoryPile\('(unassigned|storage|transfer|club)'\);/g) || []).toHaveLength(4);
    expect(source).not.toMatch(/(^|[^.\w])localStorage\.(?:getItem|setItem|removeItem)\s*\(/m);
    expect(source).not.toMatch(/\bGM_xmlhttpRequest\s*\(/);
    expect(source).not.toMatch(/(^|[^.\w])fetch\s*\(/m);
    expect(source).not.toMatch(/function\s+request(?:Price)?Text\s*\(/);
    expect(source).toContain('adapters.http.getText');
    expect(source).not.toMatch(/function\s+normalizeFsuSettings\s*\(/);
    expect(source).not.toMatch(/function\s+normalizeLockedPlayerIds\s*\(/);
    expect(source).not.toMatch(/function\s+readFsuSettingsFromStorage\s*\(/);
    expect(source).not.toMatch(/function\s+readFsuLockedPlayersFromStorage\s*\(/);
    expect(source).not.toMatch(/function\s+(?:readFsuSettingsFromInfo|readFsuSettingsFromWindow|readFsuLockedPlayersFromWindow|readFsuLockedPlayers)\s*\(/);
    expect(source).not.toMatch(/\bW\.info\b/);
    expect(source).toContain('fsuAdapter().snapshot(state.fsuSettingsOverride)');
    expect(source).toContain("from './config/fsu-compat.js'");
    expect(source).not.toMatch(/function\s+runInventoryMixedUpgrade(?:DryRun)?\s*\(/);
    expect(source).toMatch(/function\s+runSupplyAndCraftLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runDailySingleCardRecycle(?:DryRun)?\s*\(/);
    expect(source).toMatch(/function\s+runRecycleLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runCommonGoldToRareUpgrade(?:DryRun)?\s*\(/);
    expect(source).not.toMatch(/function\s+runRarePackTo84Upgrade(?:DryRun)?\s*\(/);
    expect(source).toMatch(/function\s+runRarePackCraftLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runPlayerPickSbc(?:DryRun)?\s*\(/);
    expect(source).toMatch(/function\s+runPlayerPickLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runProvisionPackCrafting(?:DryRun)?\s*\(/);
    expect(source).toMatch(/function\s+runProvisionCraftLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runFillAndVerifySbc\s*\(/);
    expect(source).not.toMatch(/\brunFillAndVerifySbc\s*\(/);
    expect(source).toMatch(/function\s+runFillAndVerifyLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runDryRunLoop\s*\(/);
    expect(source).not.toMatch(/function\s+runValidationBronzeUpgradeDryRun\s*\(/);
    expect(source).not.toMatch(/function\s+runReservedDuplicateUpgradeDryRun\s*\(/);
    expect(source).not.toMatch(/function\s+submitReservedDuplicateUpgrade\s*\(/);
    expect(source).toMatch(/function\s+runReservedDuplicateCraftingStage\s*\(/);
    expect(source).not.toMatch(/function\s+rankPlayerPickCandidates\s*\(/);
    expect(source).not.toMatch(/function\s+capturePlayerPickSelections\s*\(/);
    expect(source).not.toMatch(/function\s+getManualPickReason\s*\(/);
    expect(source).not.toMatch(/function\s+waitForManualPlayerPick\s*\(/);
    expect(source).not.toMatch(/function\s+(?:getPanelDefaultSize|resetPanelSize|makePanelDraggable|makePanelResizable|savePanelPos|getSavedPanelPos)\s*\(/);
    expect(source).toContain("from './ui/main-panel-geometry.js'");
    expect(source).toContain('createMainPanelGeometry({');
    expect(source).toContain("from './ui/main-panel-view.js'");
    expect(source).toContain("from './ui/main-panel-bindings.js'");
    expect(source).toContain("from './ui/main-panel-commands.js'");
    expect(source).toContain("from './ui/main-panel-state.js'");
    expect(source).toContain('startupHidden: true,');
    expect(source).toContain('setMainPanelStartupHidden(panel, false);');
    expect(source).toContain('hydrateMainPanelOptions({');
    expect(source).toContain('const panelCommands = createMainPanelCommands({');
    expect(source).toContain('openBatch: openBatchOpenDialogModal,');
    expect(source).toContain('reopenRecap: reopenLastRecap,');
    expect(source).toContain('bindMainPanelCommands({');
    expect(source).toContain('commands: panelCommands,');
    expect(source).toContain('await panelCommands.scanPicks();');
    expect(source).toContain('renderMainPanelRuntimeState({');
    expect(source).not.toContain('style.textContent = `');
    expect(source).not.toContain('panel.innerHTML = `');
    expect(source).not.toMatch(/function\s+(?:isPlayerPickItem|pickItemName|playerPickMatchesLoop|getPlayerPickOwnedItems|sameLimitedUseType)\s*\(/);
    expect(source).toContain('eaPlayerPickAdapter().listUnassignedPlayerPicks()');
    expect(source).toContain('eaPlayerPickAdapter().isOwnedDuplicate(item)');
    expect(source).toContain("from './ui/player-pick-modal.js'");
    expect(source).toContain("from './ui/player-pick-recap.js'");
    expect(source).toContain("from './ui/sbc-reward-overlay.js'");
    expect(source).toContain('return showPlayerPickRecap({');
    expect(source).not.toMatch(/function\s+triggerRecapFireworks\s*\(/);
    expect(source).not.toContain("overlay.id = 'bronze-loop-recap-modal'");
    expect(source).toContain('const waitAdapter = adapters.wait({ sleep, stopPoint, log });');
    expect(source).toContain('return waitAdapter.observableOnce(observable, controller, timeoutMs, label);');
    expect(source).not.toMatch(/function\s+observeOnce\([^)]*\)\s*\{\s*return\s+new\s+Promise/);
    expect(source).not.toMatch(/\bnavigator\.clipboard\b|\bnew\s+Blob\b|\bURL\.(?:createObjectURL|revokeObjectURL)\b/);
    expect(source).not.toMatch(/\bnew\s+(?:PointerEvent|MouseEvent|KeyboardEvent)\s*\(/);
    expect(source).toContain('return adapters.dom.click(el);');
    expect(source).toContain("from './selection/rating-model.js'");
    expect(source).toContain("from './selection/rating-candidates.js'");
    expect(source).toContain('return parseRatingSbcChallengePure({');
    expect(source).not.toMatch(/function\s+(?:requirementFirstKey|flattenRequirementValues|requirementValues|itemMatchesDynamicRequirement)\s*\(/);
    expect(source).not.toMatch(/function\s+(?:comparePileSelections|mergePileCounts|ratingGroupSelectionOptions|buildRatingMaterializationContext|materializeRatingVector)\s*\(/);
    expect(source).toContain("from './config/loop-schema.js'");
    expect(source).toContain("from './config/loops.js'");
    expect(source).toContain("from './config/run-limits.js'");
    expect(source).toContain("from './config/routine-steps.js'");
    expect(source).toContain("from './config/runtime-options.js'");
    expect(source).toMatch(/import\s*\{[^}]*\bapplyPickRuntimeOptions\b[^}]*\}\s*from '\.\/config\/runtime-options\.js'/s);
    expect(source).not.toMatch(/function\s+applyPickRuntimeOptions\s*\(/);
    expect(source).toContain('applyPickRuntimeOptions(pickDef, getPickRuntimeOptions());');
    expect(source).not.toMatch(/\bconst\s+LOOP_DEFS\s*=\s*\[/);
    expect(source).toContain('return claimSbcRewards({');
    expect(source).not.toMatch(/while\s*\(Date\.now\(\)\s*-\s*start\s*<\s*25000\)/);
    expect(source).not.toMatch(/function\s+(?:validateStringArray|validateNumberArray|validatePileList|validateCardSpec|validateRequirements|validateUpgradeDef|validateShortagePacks|validateRecoveryAction|validateRecoveryRecipeList|validateRecoveryPolicyList|validateRecoveryPolicyIds)\s*\(/);
    expect(source).toContain("from './sbc/navigation-sync.js'");
    expect(source).toContain("from './sbc/background-submit-retry.js'");
    expect(source).toContain("from './pack/retry-recovery.js'");
    expect(source).toContain("from './pack/stale-pack-tracker.js'");
    expect(source).toContain("from './unassigned/confirmation.js'");
    expect(source).not.toMatch(/www\.fut\.gg\/api\/fut\/player-prices/);
    expect(source).not.toMatch(/enhancer-api\.futnext\.com\/players\/prices/);
    expect(source).not.toMatch(/function\s+clear(?:MixedUpgrade)?Unassigned\s*\(/);
    expect(source).not.toMatch(/\bclear(?:MixedUpgrade)?Unassigned\s*\(/);
    expect(source).toMatch(/function\s+resolveRuntimeUnassigned\s*\(/);
    expect(source).not.toMatch(/function\s+runDailyRoutine\s*\(/);
    expect(source).toMatch(/function\s+runDailySequence\s*\(/);
    expect(source).toContain("from './workflows/dispatch.js'");
    expect(source).not.toMatch(/function\s+executeConfiguredLoopInternal\s*\(/);
    expect(source).not.toMatch(/function\s+(?:setLoopDefs|getEditorLoopStrategy|findBronzeUpgradeSet|isEligibleTotwForLoop|getEligibleTotwEntries|summarizeTotwEntries|sortTotwEntriesForSubmit|isCommonGoldPlayer|isCommonGoldDuplicate|isLowCommonGoldDuplicate)\s*\(/);
  });

  it('logs rating shortage or submit-not-ready reasons before automatic 2x84+ recovery', async () => {
    const source = await readFile(path.join(root, 'src', 'userscript-entry.js'), 'utf8');
    const shortageIdx = source.indexOf("configuredFill.ratingShortage && autoFodderAttempts < autoFodderLimit");
    const shortageCraftIdx = source.indexOf('craftAutoFodderUpgrade(loopDef, nextAttempt, autoFodderLimit)', shortageIdx);
    expect(shortageIdx).toBeGreaterThan(-1);
    expect(shortageCraftIdx).toBeGreaterThan(shortageIdx);
    const shortageWindow = source.slice(shortageIdx, shortageCraftIdx);
    expect(shortageWindow).toContain('rating shortage before automatic 2x84+ recovery');
    expect(shortageWindow).toContain('configuredFill.reason');

    const submitIdx = source.indexOf('!fillResult.submitReady &&');
    const submitCraftIdx = source.indexOf('craftAutoFodderUpgrade(loopDef, nextAttempt, autoFodderLimit)', submitIdx);
    expect(submitIdx).toBeGreaterThan(-1);
    expect(submitCraftIdx).toBeGreaterThan(submitIdx);
    const submitWindow = source.slice(submitIdx, submitCraftIdx);
    expect(submitWindow).toContain('submit not ready before automatic 2x84+ recovery');
  });

  it('requires every userscript pack call to provide an opened-item policy', async () => {
    const source = await readFile(path.join(root, 'src', 'userscript-entry.js'), 'utf8');
    expect(source).not.toMatch(/const\s+items\s*=\s*await\s+openPack\s*\(/);
    expect(source).not.toMatch(/function\s+handle(?:Recycle|Provision|RarePackTo84|RareSource)PackItems\s*\(/);
    expect(source).toContain('Opened item policy is required for');
    const packCalls = source.match(/await\s+openPack\s*\(/g) || [];
    const explicitPolicies = source.split(/\r?\n/).filter((line) =>
      line.includes('openedItemPolicy:') && !line.includes('options.openedItemPolicy')
    );
    expect(packCalls).toHaveLength(8);
    expect(explicitPolicies).toHaveLength(packCalls.length);
    expect(source).toContain('runBatchOpenWorkflow({');
    expect(source).toMatch(/runBatchOpenWorkflow\(\{[\s\S]*?openPack:\s*async[\s\S]*?openedItemPolicy:\s*createMaterializeAndResolvePolicy/);
    expect(source).toMatch(/Batch Open[\s\S]*?createMaterializeAndResolvePolicy\([\s\S]*?blockedPolicy:\s*['"]preserve['"]/);
    expect(source).toMatch(/Batch Open[\s\S]*?createMaterializeAndResolvePolicy\([\s\S]*?enableRecovery:\s*true/);
    expect(source).toMatch(/beforeStart:[\s\S]*?Batch Open preflight[\s\S]*?blockedPolicy:\s*['"]preserve['"][\s\S]*?enableRecovery:\s*true/);
    expect(source).not.toContain("resolveRuntimeUnassigned('Batch Open final cleanup')");
  });
});
