import { CFG } from './runtime.js';

export const LOOP_DEFS = [
  {
    id: 'bronze-upgrade-validation',
    hidden: true,
    mvp: true,
    name: 'Bronze Upgrade Validation',
    strategy: 'validationBronzeUpgrade',
    activityBinding: { family: 'bronze-upgrade', category: 'Upgrades', required: true },
    sourcePackIds: [105],
    sourcePackNames: CFG.sourcePackNames,
    sbcNames: CFG.bronzeUpgradeNames,
    rewardPackNames: CFG.silverRewardNames,
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    maxRounds: 3,
    runtimeQuantity: { mode: 'user', target: 'validationRounds', default: 3, min: 1, max: 50, label: 'Validation runs' },
  },
  {
    id: 'daily-bronze',
    hidden: true,
    name: 'Daily Bronze Loop',
    strategy: 'dailySingleCardRecycle',
    activityBinding: { family: 'daily-bronze-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Bronze Upgrade', '每日青铜升级', '每日青銅升級'],
    rewardPackIds: [105],
    rewardPackNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 7,
    inventoryMode: 'inherit',
  },
  {
    id: 'daily-bronze-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Bronze MVP (1 run)',
    strategy: 'dailySingleCardRecycle',
    activityBinding: { family: 'daily-bronze-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Bronze Upgrade', '每日青铜升级', '每日青銅升級'],
    rewardPackIds: [105],
    rewardPackNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 1,
    inventoryMode: 'inherit',
  },
  {
    id: 'daily-silver',
    hidden: true,
    name: 'Daily Silver Loop',
    strategy: 'dailySingleCardRecycle',
    activityBinding: { family: 'daily-silver-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Silver Upgrade', '每日白银升级', '每日白銀升級'],
    rewardPackIds: [205],
    rewardPackNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'silver', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 7,
    inventoryMode: 'inherit',
  },
  {
    id: 'daily-silver-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Silver MVP (1 run)',
    strategy: 'dailySingleCardRecycle',
    activityBinding: { family: 'daily-silver-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Silver Upgrade', '每日白银升级', '每日白銀升級'],
    rewardPackIds: [205],
    rewardPackNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'silver', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 1,
    inventoryMode: 'inherit',
  },
  {
    id: 'daily-common',
    hidden: true,
    name: 'Daily Common Loop',
    strategy: 'supplyAndCraft',
    activityBinding: { family: 'daily-common-gold-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Common Gold Upgrade', '每日普通金牌升级', '每日普通金牌升級'],
    rewardPackIds: [304],
    rewardPackNames: ['Gold Players Pack'],
    requirements: [
      { tier: 'silver', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
      { tier: 'bronze', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
    ],
    priorityPiles: ['storage', 'transfer', 'club'],
    primaryPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    shortagePacks: [
      { requirement: { tier: 'bronze' }, packIds: [105], packNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'], maxOpensPerAttempt: 1, routingPolicy: 'reserveMatchingDuplicates' },
      { requirement: { tier: 'silver' }, packIds: [205], packNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'], maxOpensPerAttempt: 1, routingPolicy: 'reserveMatchingDuplicates' },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-common-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Common MVP (1 run)',
    strategy: 'supplyAndCraft',
    activityBinding: { family: 'daily-common-gold-upgrade', category: 'Upgrades', required: true },
    sbcNames: ['Daily Common Gold Upgrade', '每日普通金牌升级', '每日普通金牌升級'],
    rewardPackIds: [304],
    rewardPackNames: ['Gold Players Pack'],
    requirements: [
      { tier: 'silver', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
      { tier: 'bronze', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
    ],
    priorityPiles: ['storage', 'transfer', 'club'],
    primaryPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    shortagePacks: [
      { requirement: { tier: 'bronze' }, packIds: [105], packNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'], maxOpensPerAttempt: 1, routingPolicy: 'reserveMatchingDuplicates' },
      { requirement: { tier: 'silver' }, packIds: [205], packNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'], maxOpensPerAttempt: 1, routingPolicy: 'reserveMatchingDuplicates' },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-rare',
    hidden: true,
    name: 'Daily Rare Loop',
    strategy: 'supplyAndCraft',
    activityBinding: { family: 'daily-rare-gold-upgrade', category: 'Upgrades', required: true },
    sourcePackRef: { rewardOfLoopId: 'daily-common' },
    sbcNames: ['Daily Rare Gold Upgrade', '每日稀有金牌升级', '每日稀有金牌升級'],
    sourcePackIds: [20060],
    sourcePackNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
    rewardPackIds: [20059],
    rewardPackNames: ['Max. 78 Rare Gold Players Pack', 'Max 78 Rare Gold Players Pack'],
    requirements: [
      { tier: 'gold', rarity: 'common', count: 5, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer'] },
    ],
    priorityPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    deferChallengeLoad: true,
    preSelectionCleanup: false,
    shortagePacks: [
      {
        sourcePackRef: { rewardOfLoopId: 'daily-common' },
        requirement: { tier: 'gold', rarity: 'common', playerOnly: true, allowSpecial: false, protectHighGold: true },
        packIds: [20060],
        packNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
        maxOpensPerAttempt: 1,
        repeatUntilSatisfied: true,
        maxRuns: 100,
        routingPolicy: 'reserveMatchingDuplicates',
      },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-rare-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Rare MVP (1 run)',
    strategy: 'supplyAndCraft',
    activityBinding: { family: 'daily-rare-gold-upgrade', category: 'Upgrades', required: true },
    sourcePackRef: { rewardOfLoopId: 'daily-common-mvp' },
    sbcNames: ['Daily Rare Gold Upgrade', '每日稀有金牌升级', '每日稀有金牌升級'],
    sourcePackIds: [20060],
    sourcePackNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
    rewardPackIds: [20059],
    rewardPackNames: ['Max. 78 Rare Gold Players Pack', 'Max 78 Rare Gold Players Pack'],
    requirements: [
      { tier: 'gold', rarity: 'common', count: 5, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer'] },
    ],
    priorityPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    deferChallengeLoad: true,
    preSelectionCleanup: false,
    shortagePacks: [
      {
        sourcePackRef: { rewardOfLoopId: 'daily-common-mvp' },
        requirement: { tier: 'gold', rarity: 'common', playerOnly: true, allowSpecial: false, protectHighGold: true },
        packIds: [20060],
        packNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
        maxOpensPerAttempt: 1,
        repeatUntilSatisfied: true,
        maxRuns: 100,
        routingPolicy: 'reserveMatchingDuplicates',
      },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-rare-pack-84',
    name: 'Daily Rare Pack to 2x84+ Loop',
    strategy: 'rarePackTo84Upgrade',
    sourcePackRef: { rewardOfLoopId: 'daily-rare' },
    sourcePackIds: [20059],
    sourcePackNames: [
      '5x Max.78 Rare Gold Players Pack',
      '5x Max. 78 Rare Gold Players Pack',
      '5x Max 78 Rare Gold Players Pack',
      '5 x Max.78 Rare Gold Players Pack',
      '5 x Max. 78 Rare Gold Players Pack',
      '5 x Max 78 Rare Gold Players Pack',
      '5x 80+ Rare Gold Players Pack',
      '5 x 80+ Rare Gold Players Pack',
    ],
    rareUpgrade: {
      name: '2x 84+ Upgrade',
      activityBinding: { family: '2x84-upgrade', category: 'Upgrades', required: true },
      sbcNames: ['2x 84+ Upgrade', '2 x 84+ Upgrade'],
      requirements: [
        { tier: 'gold', rarity: 'rare', count: 6, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
      ],
      priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    },
    maxPacks: 100,
    maxCompletions: 1,
    useRoundsAsCompletions: true,
    runtimeQuantity: { mode: 'user', target: 'maxCompletions', default: 3, min: 1, max: 50, label: 'SBC completions' },
    consumeAllSourcePacks: true,
    sourceExhaustedFallbackActivityFamily: '2x84-upgrade',
  },
  {
    id: 'one-click-daily-mvp',
    hidden: true,
    mvp: true,
    name: 'One-click Daily MVP (1 each)',
    strategy: 'dailyRoutine',
    steps: ['daily-bronze-mvp', 'daily-silver-mvp', 'daily-common-mvp', 'daily-rare-mvp'],
    openRewardPacks: false,
  },
  {
    id: 'one-click-daily',
    name: 'One-click Daily Loop',
    strategy: 'dailyRoutine',
    steps: ['daily-bronze', 'daily-silver', 'daily-common', 'daily-rare'],
    openRewardPacks: false,
  },
  {
    id: 'inventory-fodder-exhaustion',
    name: 'Bronze/Silver/5x 80+ Exhaustion Loop',
    strategy: 'inventoryExhaustion',
    openRewardPacksAtEnd: true,
    rewardPackNames: [
      '5x 80+ Rare Gold Players Pack',
      '5 x 80+ Rare Gold Players Pack',
      'x1 5x 80+ Rare Gold Players Pack',
      '5x80+ Rare Gold Players Pack',
      '5x 80+ Rare Gold Players Pack (Untradeable)',
    ],
    stages: [
      {
        id: 'bronze-upgrade',
        name: 'Bronze Upgrade',
        activityBinding: { family: 'bronze-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['Bronze Upgrade', '青铜升级', '青銅升級'],
        requirements: [
          { tier: 'bronze', count: 11, playerOnly: true, allowSpecial: false, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
        maxCompletions: 1000,
        openRewardPacks: true,
        forceOpenRewardPacks: true,
      },
      {
        id: 'silver-upgrade',
        name: 'Silver Upgrade',
        activityBinding: { family: 'silver-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['Silver Upgrade', '白银升级', '白銀升級'],
        requirements: [
          { tier: 'silver', count: 11, playerOnly: true, allowSpecial: false, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
        maxCompletions: 1000,
        openRewardPacks: true,
        forceOpenRewardPacks: true,
      },
      {
        id: 'fof-glory-hunters',
        name: '5x 80+ Upgrade',
        activityBinding: { family: 'common-gold-crafting-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['5x 80+ Upgrade'],
        requirements: [
          {
            tier: 'gold',
            rarity: 'common',
            count: 9,
            maxRating: 81,
            playerOnly: true,
            allowSpecial: false,
            protectHighGold: true,
            priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
          },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
        maxCompletions: 1000,
      },
    ],
  },
  {
    id: 'fof-glory-hunters-exhaustion',
    name: '5x 80+ Exhaustion Loop',
    strategy: 'inventoryExhaustion',
    openRewardPacksAtEnd: true,
    rewardPackNames: [
      '5x 80+ Rare Gold Players Pack',
      '5 x 80+ Rare Gold Players Pack',
      'x1 5x 80+ Rare Gold Players Pack',
      '5x80+ Rare Gold Players Pack',
      '5x 80+ Rare Gold Players Pack (Untradeable)',
    ],
    stages: [
      {
        id: 'fof-glory-hunters',
        name: '5x 80+ Upgrade',
        activityBinding: { family: 'common-gold-crafting-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['5x 80+ Upgrade'],
        requirements: [
          {
            tier: 'gold',
            rarity: 'common',
            count: 9,
            maxRating: 81,
            playerOnly: true,
            allowSpecial: false,
            protectHighGold: true,
            priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
          },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
        maxCompletions: 1000,
      },
    ],
  },
  {
    id: 'provision-crafting',
    name: 'Provision Crafting Loop',
    strategy: 'provisionPackCrafting',
    sourcePackIds: [20643],
    sourcePackNames: ['Provision Pack', 'Provisions Pack'],
    preCraftPlayerPickSelector: { material: 'common-gold' },
    rounds: 1,
    runtimeQuantity: { mode: 'user', target: 'rounds', default: 1, min: 1, max: 50, label: 'Provision packs' },
    craftingUpgrades: [
      {
        name: '5x 80+ Upgrade',
        activityBinding: { family: 'common-gold-crafting-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['5x 80+ Upgrade'],
        requirements: [
          { tier: 'gold', rarity: 'common', count: 9, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
      },
      {
        name: '2x 84+ Upgrade',
        activityBinding: { family: '2x84-upgrade', category: 'Upgrades', required: true },
        sbcNames: ['2x 84+ Upgrade', '2 x 84+ Upgrade'],
        requirements: [
          { tier: 'gold', rarity: 'rare', count: 6, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
      },
    ],
  },
];
