import { CFG } from './runtime.js';

export const LOOP_DEFS = [
  {
    id: 'bronze-upgrade-validation',
    hidden: true,
    mvp: true,
    name: 'Bronze Upgrade Validation',
    strategy: 'validationBronzeUpgrade',
    sourcePackIds: [105],
    sourcePackNames: CFG.sourcePackNames,
    sbcNames: CFG.bronzeUpgradeNames,
    rewardPackNames: CFG.silverRewardNames,
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    maxRounds: 3,
  },
  {
    id: 'daily-bronze',
    hidden: true,
    name: 'Daily Bronze Loop',
    strategy: 'dailySingleCardRecycle',
    sbcNames: ['Daily Bronze Upgrade', '每日青铜升级', '每日青銅升級'],
    rewardPackIds: [105],
    rewardPackNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-bronze-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Bronze MVP (1 run)',
    strategy: 'dailySingleCardRecycle',
    sbcNames: ['Daily Bronze Upgrade', '每日青铜升级', '每日青銅升級'],
    rewardPackIds: [105],
    rewardPackNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'bronze', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-silver',
    hidden: true,
    name: 'Daily Silver Loop',
    strategy: 'dailySingleCardRecycle',
    sbcNames: ['Daily Silver Upgrade', '每日白银升级', '每日白銀升級'],
    rewardPackIds: [205],
    rewardPackNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'silver', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-silver-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Silver MVP (1 run)',
    strategy: 'dailySingleCardRecycle',
    sbcNames: ['Daily Silver Upgrade', '每日白银升级', '每日白銀升級'],
    rewardPackIds: [205],
    rewardPackNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'],
    targetDuplicate: { tier: 'silver', playerOnly: true, allowSpecial: false },
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-common',
    hidden: true,
    name: 'Daily Common Loop',
    strategy: 'supplyAndCraft',
    sbcNames: ['Daily Common Gold Upgrade', '每日普通金牌升级', '每日普通金牌升級'],
    rewardPackIds: [304],
    rewardPackNames: ['Gold Players Pack'],
    requirements: [
      { tier: 'silver', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
      { tier: 'bronze', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
    ],
    priorityPiles: ['storage', 'transfer', 'club'],
    primaryPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    shortagePacks: [
      { requirement: { tier: 'bronze' }, packIds: [105], packNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'], maxOpensPerAttempt: 1 },
      { requirement: { tier: 'silver' }, packIds: [205], packNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'], maxOpensPerAttempt: 1 },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-common-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Common MVP (1 run)',
    strategy: 'supplyAndCraft',
    sbcNames: ['Daily Common Gold Upgrade', '每日普通金牌升级', '每日普通金牌升級'],
    rewardPackIds: [304],
    rewardPackNames: ['Gold Players Pack'],
    requirements: [
      { tier: 'silver', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
      { tier: 'bronze', count: 5, playerOnly: true, allowSpecial: false, priorityPiles: ['storage', 'transfer', 'club'] },
    ],
    priorityPiles: ['storage', 'transfer', 'club'],
    primaryPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    shortagePacks: [
      { requirement: { tier: 'bronze' }, packIds: [105], packNames: ['Bronze Players Premium', 'Premium Bronze Players', 'BRONZE PLAYERS PREMIUM'], maxOpensPerAttempt: 1 },
      { requirement: { tier: 'silver' }, packIds: [205], packNames: ['Silver Players Premium', 'SILVER PLAYERS PREMIUM'], maxOpensPerAttempt: 1 },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-rare',
    hidden: true,
    name: 'Daily Rare Loop',
    strategy: 'supplyAndCraft',
    sbcNames: ['Daily Rare Gold Upgrade', '每日稀有金牌升级', '每日稀有金牌升級'],
    sourcePackNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
    rewardPackNames: ['Max. 78 Rare Gold Players Pack', 'Max 78 Rare Gold Players Pack'],
    requirements: [
      { tier: 'gold', rarity: 'common', count: 5, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer'] },
    ],
    priorityPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    deferChallengeLoad: true,
    preSelectionCleanup: false,
    shortagePacks: [
      {
        requirement: { tier: 'gold', rarity: 'common', playerOnly: true, allowSpecial: false, protectHighGold: true },
        packNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
        maxOpensPerAttempt: 1,
        repeatUntilSatisfied: true,
        maxRuns: 100,
        routingPolicy: 'reserveMatchingDuplicates',
      },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 7,
  },
  {
    id: 'daily-rare-mvp',
    hidden: true,
    mvp: true,
    name: 'Daily Rare MVP (1 run)',
    strategy: 'supplyAndCraft',
    sbcNames: ['Daily Rare Gold Upgrade', '每日稀有金牌升级', '每日稀有金牌升級'],
    sourcePackNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
    rewardPackNames: ['Max. 78 Rare Gold Players Pack', 'Max 78 Rare Gold Players Pack'],
    requirements: [
      { tier: 'gold', rarity: 'common', count: 5, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer'] },
    ],
    priorityPiles: ['unassigned', 'storage', 'transfer'],
    clubFallbackPiles: ['unassigned', 'storage', 'transfer', 'club'],
    deferChallengeLoad: true,
    preSelectionCleanup: false,
    shortagePacks: [
      {
        requirement: { tier: 'gold', rarity: 'common', playerOnly: true, allowSpecial: false, protectHighGold: true },
        packNames: ['11x Gold Players Pack', '11 x Gold Players Pack'],
        maxOpensPerAttempt: 1,
        repeatUntilSatisfied: true,
        maxRuns: 100,
        routingPolicy: 'reserveMatchingDuplicates',
      },
    ],
    dailyCompletionLimit: 7,
    maxCompletions: 1,
  },
  {
    id: 'daily-rare-pack-84',
    name: 'Daily Rare Pack to 2x84+ Loop',
    strategy: 'rarePackTo84Upgrade',
    sourcePackNames: [
      '5x Max.78 Rare Gold Players Pack',
      '5x Max. 78 Rare Gold Players Pack',
      '5x Max 78 Rare Gold Players Pack',
      '5 x Max.78 Rare Gold Players Pack',
      '5 x Max. 78 Rare Gold Players Pack',
      '5 x Max 78 Rare Gold Players Pack',
      '5x 80+ Rare Gold Players Pack',
      '5 x 80+ Rare Gold Players Pack',
    ],
    rareUpgrade: {
      name: '2x 84+ Upgrade',
      sbcNames: ['2x 84+ Upgrade', '2 x 84+ Upgrade'],
      requirements: [
        { tier: 'gold', rarity: 'rare', count: 6, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
      ],
      priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    },
    maxPacks: 100,
    maxCompletions: 1,
    useRoundsAsCompletions: true,
    consumeAllSourcePacks: true,
    sourceExhaustedFallbackLoopId: '2x84-fodder',
  },
  {
    id: '82-plus-player-pick-5of10',
    name: '5 of 10 82+ Players Pick',
    strategy: 'playerPickSbc',
    sbcSetIds: [1202],
    sbcNames: ['5 of 10 82+ Players Pick', '5 of 10 82+ Player Pick', '5 of 10 82+ Player Picks'],
    pickItemResourceIds: [5005706],
    pickItemNames: ['5 of 10 82+ Players Pick', '5 of 10 82+ Player Pick', '5 of 10 82+ Rare Gold Player Pick', '82+ Player Pick'],
    requirements: [
      { tier: 'gold', rarity: 'common', count: 11, maxRating: 81, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
    ],
    priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    challengesPerPick: 2,
    pickCandidateCount: 10,
    pickCount: 5,
    exhaustSbcSet: true,
    setCompletionSafetyLimit: 100,
    pricePlatform: 'pc',
  },
  {
    id: 'one-click-daily-mvp',
    hidden: true,
    mvp: true,
    name: 'One-click Daily MVP (1 each)',
    strategy: 'dailyRoutine',
    steps: ['daily-bronze-mvp', 'daily-silver-mvp', 'daily-common-mvp', 'daily-rare-mvp'],
    openRewardPacks: false,
  },
  {
    id: 'one-click-daily',
    name: 'One-click Daily Loop',
    strategy: 'dailyRoutine',
    steps: ['daily-bronze', 'daily-silver', 'daily-common', 'daily-rare', 'daily-rare-pack-84'],
    stepOverrides: {
      'daily-rare-pack-84': {
        useRoundsAsCompletions: false,
        sourceExhaustedFallbackMaxCompletions: 1,
      },
    },
    openRewardPacks: false,
  },
  {
    id: '2x84-fodder',
    hidden: true,
    mvp: true,
    name: '2x84+ Fodder Loop',
    strategy: 'fillAndVerifySbc',
    sbcNames: ['2x 84+ Upgrade', '2 x 84+ Upgrade'],
    rewardPackNames: ['2x 84+ Rare Gold Players Pack', '2 x 84+ Rare Gold Players Pack'],
    maxCompletions: 1,
    useRoundsAsCompletions: true,
    allowMultipleCompletions: true,
    inventoryFillFirst: true,
    requirements: [
      { tier: 'gold', rarity: 'rare', count: 6, maxRating: 81, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['storage', 'club'] },
    ],
    priorityPiles: ['storage', 'club'],
    requiredSpecialCount: 0,
    allowedSpecialCount: 0,
    maxSubmittedRating: 81,
    maxNormalGoldSubmittedRating: 81,
    blockSpecial: true,
    blockTradeable: false,
    openRewardPacks: true,
  },
  {
    id: 'auto-totw-upgrade',
    name: '84+ TOTW Upgrade Loop',
    strategy: 'fillAndVerifySbc',
    sbcNames: ['84+ TOTW Upgrade', '84+ TOTW', 'TOTW Upgrade', '84+ TOTW 升级', '84+ TOTW 升級'],
    rewardPackIds: [20707, 20441],
    rewardPackNames: ['84+ TOTW 1-30 Player Pack', 'TOTW 1-30 Player Pack', '84+ TOTW 1-30', 'TOTW 1-30', '84+ TOTW Player Pack', 'TOTW Player Pack', '84+ TOTW Pack', 'TOTW Pack', 'TOTW Provision Refresh', 'TOTW Provision Refresh Pack'],
    maxCompletions: 1,
    useRoundsAsCompletions: true,
    allowMultipleCompletions: true,
    maxSubmittedRating: 88,
    maxNormalGoldSubmittedRating: 99,
    ratingSbcFill: {
      priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    },
    requiredSpecialCount: 0,
    allowedSpecialCount: 0,
    blockSpecial: true,
    blockTradeable: false,
    openRewardPacks: true,
    forceOpenRewardPacks: true,
    assumeTotwRewardPack: true,
  },
  {
    id: '84x10-mvp',
    hidden: true,
    mvp: true,
    name: '84x10 MVP (1 run)',
    strategy: 'fillAndVerifySbc',
    sbcNames: [
      '84+ x10',
      '84+ x 10',
      '10x 84+ Upgrade',
      '10 x 84+ Upgrade',
      '10 名 84+ 升级',
      '10名84+升级',
    ],
    maxCompletions: 1,
    maxSubmittedRating: 88,
    maxNormalGoldSubmittedRating: 99,
    ratingSbcFill: {
      priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    },
    requiredSpecialCount: 1,
    allowedSpecialCount: 1,
    requiredSpecialKind: 'totw-tots-fof',
    requiredSpecialMinRating: 84,
    specialRequirementAdd: {
      patterns: ['Any TOTW/TOTS/FOF', 'TOTW/TOTS/FOF', 'TOTW', 'TOTS', 'FOF'],
      buttonTexts: ['Add', '添加', '加入', '新增'],
    },
    autoTotwUpgrade: {
      name: '84+ TOTW Upgrade',
      sbcNames: ['84+ TOTW Upgrade', '84+ TOTW', 'TOTW Upgrade', '84+ TOTW 升级', '84+ TOTW 升級'],
      rewardPackIds: [20707, 20441],
      rewardPackNames: ['84+ TOTW 1-30 Player Pack', 'TOTW 1-30 Player Pack', '84+ TOTW 1-30', 'TOTW 1-30', '84+ TOTW Player Pack', 'TOTW Player Pack', '84+ TOTW Pack', 'TOTW Pack', 'TOTW Provision Refresh', 'TOTW Provision Refresh Pack'],
      maxSubmittedRating: 88,
      maxNormalGoldSubmittedRating: 99,
      blockSpecial: true,
      blockTradeable: false,
      openRewardPacks: true,
    },
    autoFodderUpgrade: {
      maxAttemptsPerCompletion: 3,
    },
    blockSpecial: true,
    blockTradeable: false,
    openRewardPacks: false,
  },
  {
    id: '84x10',
    name: '84x10 Loop',
    strategy: 'fillAndVerifySbc',
    sbcNames: [
      '84+ x10',
      '84+ x 10',
      '10x 84+ Upgrade',
      '10 x 84+ Upgrade',
      '10 名 84+ 升级',
      '10名84+升级',
    ],
    maxCompletions: 50,
    allowMultipleCompletions: true,
    maxSubmittedRating: 88,
    maxNormalGoldSubmittedRating: 99,
    ratingSbcFill: {
      priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
    },
    requiredSpecialCount: 1,
    allowedSpecialCount: 1,
    requiredSpecialKind: 'totw-tots-fof',
    requiredSpecialMinRating: 84,
    specialRequirementAdd: {
      patterns: ['Any TOTW/TOTS/FOF', 'TOTW/TOTS/FOF', 'TOTW', 'TOTS', 'FOF'],
      buttonTexts: ['Add', '添加', '加入', '新增'],
    },
    autoTotwUpgrade: {
      name: '84+ TOTW Upgrade',
      sbcNames: ['84+ TOTW Upgrade', '84+ TOTW', 'TOTW Upgrade', '84+ TOTW 升级', '84+ TOTW 升級'],
      rewardPackIds: [20707, 20441],
      rewardPackNames: ['84+ TOTW 1-30 Player Pack', 'TOTW 1-30 Player Pack', '84+ TOTW 1-30', 'TOTW 1-30', '84+ TOTW Player Pack', 'TOTW Player Pack', '84+ TOTW Pack', 'TOTW Pack', 'TOTW Provision Refresh', 'TOTW Provision Refresh Pack'],
      maxSubmittedRating: 88,
      maxNormalGoldSubmittedRating: 99,
      blockSpecial: true,
      blockTradeable: false,
      openRewardPacks: true,
    },
    autoFodderUpgrade: {
      maxAttemptsPerCompletion: 3,
    },
    blockSpecial: true,
    blockTradeable: false,
    openRewardPacks: false,
  },
  {
    id: 'provision-crafting',
    name: 'Provision Crafting Loop',
    strategy: 'provisionPackCrafting',
    sourcePackIds: [20643],
    sourcePackNames: ['Provision Pack', 'Provisions Pack'],
    preCraftPlayerPickLoopId: '82-plus-player-pick-5of10',
    rounds: 1,
    craftingUpgrades: [
      {
        name: 'FOF Glory Hunters Crafting Upgrade',
        sbcNames: ['FOF Glory Hunters Crafting Upgrade'],
        requirements: [
          { tier: 'gold', rarity: 'common', count: 9, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
      },
      {
        name: '2x 84+ Upgrade',
        sbcNames: ['2x 84+ Upgrade', '2 x 84+ Upgrade'],
        requirements: [
          { tier: 'gold', rarity: 'rare', count: 6, playerOnly: true, allowSpecial: false, protectHighGold: true, priorityPiles: ['unassigned', 'storage', 'transfer', 'club'] },
        ],
        priorityPiles: ['unassigned', 'storage', 'transfer', 'club'],
      },
    ],
  },
];
